# Generated by Django 5.1.4 on 2026-01-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('employee', 'Employee'), ('visitor', 'Visitor')], max_length=10)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(max_length=20)),
                ('vehicle_no', models.CharField(max_length=20)),
                ('purpose', models.CharField(blank=True, max_length=200, null=True)),
                ('booking_date', models.CharField(max_length=50)),
                ('time_slot', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
