# Generated by Django 5.1.4 on 2026-01-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='allocated_slot',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
