# Generated by Django 5.1.4 on 2026-01-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pass_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='daily', max_length=10),
        ),
    ]
